name: Build and generate docs

on:
    push:
        branches-ignore:
            - docs
    pull_request:
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                java: [17]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v1
              with:
                  java-package: jdk
                  java-version: ${{ matrix.java }}

            - name: Make Gradle executable
              if: ${{ runner.os != 'Windows' }}
              run: chmod +x gradlew

            - name: Build using Gradle
              run: ./gradlew build
